1. Create a 5X2 integer array from a range between 100 ato 200 such that the difference between each element is 10

In [1]:
import numpy as np

In [3]:
arr = np.arange(100, 200, 10)
arr = arr.reshape(5, 2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Return array of odd rows and even columns from the given numpy array

In [4]:
sampleArray = np.array([[3,6,9,12], [15,18,21,24], [27,30,33,36], [39,42,45,48], [51,54,57,60]])
print(sampleArray)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [25]:
print(sampleArray[0::2, 1::2])

[[ 6 12]
 [30 36]
 [54 60]]


3. Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [28]:
#Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

result = arrayOne + arrayTwo
print(result)

result = result * result

[[20 39 33]
 [25 25 28]]


In [29]:
print(result)

[[ 400 1521 1089]
 [ 625  625  784]]


4. Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [31]:
#create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
arr = np.arange(10, 34, 1).reshape(8, 3)
print(arr)


[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [32]:
sub_arrays = np.array_split(arr, 4)

# Print each sub-array
for sub_array in sub_arrays:
    print(sub_array)

[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]


5. Print max from axis 0 and min from axis 1 from the following 2-D array.

In [33]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [34]:
print(np.amax(sampleArray, axis=0))

print(np.amin(sampleArray, axis=1))

[82 94 73]
[34 12 53]
