In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])

In [4]:
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr = np.array(42)
print(arr)

42


In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [7]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3 = np.array([[[0,1], [2,3]], [[4,5], [6,7]]])
print(arr3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
a = np.array([(1,2,3,), (4,5,6)])
print(a.ndim)

2


In [10]:
print(arr3.ndim)

3


In [11]:
print(arr1.ndim)

1


In [12]:
print(arr.ndim)

0


In [13]:
print(arr3.dtype)

int32


In [14]:
a = a.astype('float64')

In [15]:
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
print(a.dtype)

float64


In [17]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

In [18]:
arr3.shape

(2, 2, 2)

In [19]:
arr1 = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr1)
print(arr1.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [20]:
s = s.reshape(3, 1)

In [21]:
print(s)

[['Ram']
 ['Robert']
 ['Rahim']]


In [22]:
print(arr2 + 3)

[[4 5 6]
 [7 8 9]]


In [24]:
arr2 = np.ones(4)
print(arr2)

[1. 1. 1. 1.]


In [25]:
array2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(array2)

In [28]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
d = np.eye(3,2)
print(d)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [31]:
a = np.diag([1, 2, 3, 4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [34]:
a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
x=np.array([(8,9,10),(11,12,13)])
y=np.array([(1,2,3),(4,5,6)])

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[ 9 11 13]
 [15 17 19]]
[[ 9 11 13]
 [15 17 19]]
[[7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]]
63
[19 21 23]
[27 36]
